export interface MenuModifierOption {
  id: string
  label: string
  priceAdj: number
}

export interface MenuModifierGroup {
  id: string
  label: string
  type: 'single' | 'multi'
  required: boolean
  icon?: string   // emoji shown before label
  options: MenuModifierOption[]
  /** Option ids pre-selected as the base/standard choice for new orders */
  defaultOptionIds?: string[]
}

export interface MenuItem {
  id: string
  categoryId: string
  name: string
  nameTh: string
  basePrice: number
  thumbnailPlaceholder: string
  /** Prefer local /public image over unsplashId when set */
  imagePath?: string
  unsplashId?: string
  modifierGroups: MenuModifierGroup[]
}

export interface MenuCategory {
  id: string
  label: string
  labelTh: string
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const MENU_CATEGORIES: MenuCategory[] = [
  { id: 'set',         label: 'เซตเมนู',        labelTh: 'เซตเมนู' },
  { id: 'ramen-hot',   label: 'ราเมนร้อน',      labelTh: 'ราเมนร้อน' },
  { id: 'ramen-cold',  label: 'ราเมนเย็น',      labelTh: 'ราเมนเย็น' },
  { id: 'don',         label: 'ข้าวหน้า',        labelTh: 'ข้าวหน้า' },
  { id: 'appetizers',  label: 'อาหารทานเล่น',    labelTh: 'อาหารทานเล่น' },
  { id: 'sides',       label: 'เครื่องเคียง',    labelTh: 'เครื่องเคียง' },
  { id: 'drinks',      label: 'เครื่องดื่ม',     labelTh: 'เครื่องดื่ม' },
  { id: 'desserts',    label: 'ของหวาน',          labelTh: 'ของหวาน' },
]

// ---------------------------------------------------------------------------
// Shared modifier group definitions — A Ramen actual customisation
// ---------------------------------------------------------------------------

const RAMEN_MODIFIER_GROUPS: MenuModifierGroup[] = [
  {
    id: 'noodle-firmness',
    label: 'ระดับความนุ่มของเส้น',
    icon: '🍜',
    type: 'single',
    required: true,
    defaultOptionIds: ['normal'],
    options: [
      { id: 'very-soft',   label: 'นุ่มมาก',  priceAdj: 0 },
      { id: 'soft',        label: 'นุ่ม',      priceAdj: 0 },
      { id: 'normal',      label: 'ปกติ',      priceAdj: 0 },
      { id: 'firm',        label: 'แข็ง',      priceAdj: 0 },
      { id: 'very-firm',   label: 'แข็งมาก',  priceAdj: 0 },
    ],
  },
  {
    id: 'broth-richness',
    label: 'ความเข้มข้นของน้ำซุป',
    icon: '🥣',
    type: 'single',
    required: true,
    defaultOptionIds: ['medium'],
    options: [
      { id: 'light',    label: 'เข้มข้นน้อย',  priceAdj: 0 },
      { id: 'medium',   label: 'ปานกลาง',       priceAdj: 0 },
      { id: 'rich',     label: 'เข้มข้นมาก',   priceAdj: 0 },
    ],
  },
  {
    id: 'chashu',
    label: 'หมูชาชู',
    icon: '🥩',
    type: 'single',
    required: true,
    defaultOptionIds: ['fatty'],
    options: [
      { id: 'no-pork',    label: 'ไม่ใส่หมู',                priceAdj: 0 },
      { id: 'fatty',      label: 'หมูติดมัน',               priceAdj: 0 },
      { id: 'lean',       label: 'หมูไม่ติดมัน',            priceAdj: 0 },
    ],
  },
  {
    id: 'onion',
    label: 'ต้นหอม, ต้นหอมขาวญี่ปุ่น',
    icon: '🌿',
    type: 'multi',
    required: true,
    defaultOptionIds: ['both'],
    options: [
      { id: 'none',      label: 'ไม่ใส่เลย',           priceAdj: 0 },
      { id: 'white',     label: 'ต้นหอมขาวญี่ปุ่น',    priceAdj: 0 },
      { id: 'green',     label: 'ต้นหอมเขียว',          priceAdj: 0 },
      { id: 'both',      label: 'ใส่ทั้ง 2 แบบ',        priceAdj: 0 },
    ],
  },
  {
    id: 'spice-level',
    label: 'ระดับความเผ็ด',
    icon: '🌶️',
    type: 'single',
    required: true,
    defaultOptionIds: ['no-spice'],
    options: [
      { id: 'no-spice', label: 'ไม่เผ็ดเลย', priceAdj: 0 },
      { id: 'x1',       label: 'x1',          priceAdj: 0 },
      { id: 'x2',       label: 'x2',          priceAdj: 0 },
      { id: 'x3',       label: 'x3',          priceAdj: 0 },
      { id: 'x4',       label: 'x4',          priceAdj: 0 },
      { id: 'x5',       label: 'x5',          priceAdj: 0 },
      { id: 'x6',       label: 'x6',          priceAdj: 0 },
      { id: 'x7',       label: 'x7',          priceAdj: 0 },
    ],
  },
  {
    id: 'garlic',
    label: 'กระเทียม',
    icon: '🧄',
    type: 'single',
    required: true,
    defaultOptionIds: ['1tsp'],
    options: [
      { id: 'none',  label: 'ไม่ใส่เลย',  priceAdj: 0 },
      { id: '1tsp',  label: '1 ช้อนชา',   priceAdj: 0 },
      { id: '2tsp',  label: '2 ช้อนชา',   priceAdj: 0 },
      { id: '3tsp',  label: '3 ช้อนชา',   priceAdj: 0 },
      { id: '4tsp',  label: '4 ช้อนชา',   priceAdj: 0 },
      { id: '5tsp',  label: '5 ช้อนชา',   priceAdj: 0 },
    ],
  },
  {
    id: 'broth-oil',
    label: 'ความมันของน้ำซุป',
    icon: '🫙',
    type: 'single',
    required: true,
    defaultOptionIds: ['medium'],
    options: [
      { id: 'light',   label: 'มันนิดหน่อย',  priceAdj: 0 },
      { id: 'medium',  label: 'ปานกลาง',       priceAdj: 0 },
      { id: 'rich',    label: 'มันมาก',        priceAdj: 0 },
    ],
  },
]

// ---------------------------------------------------------------------------
// Menu items — sourced from https://www.a-ramen.com/menu
// ---------------------------------------------------------------------------

export const MENU_ITEMS: MenuItem[] = [
  // ── เซตเมนู ────────────────────────────────────────────────────────────────
  {
    id: 'set-single-a',
    categoryId: 'set',
    name: 'Single Set A',
    nameTh: 'เซตเดี่ยว A',
    basePrice: 240,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862126338.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-single-b',
    categoryId: 'set',
    name: 'Single Set B',
    nameTh: 'เซตเดี่ยว B',
    basePrice: 240,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862146982.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-single-c',
    categoryId: 'set',
    name: 'Single Set C',
    nameTh: 'เซตเดี่ยว C',
    basePrice: 240,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862167426.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-pair-a',
    categoryId: 'set',
    name: 'Pair Set A',
    nameTh: 'เซตคู่ A',
    basePrice: 520,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862090264.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-pair-b',
    categoryId: 'set',
    name: 'Pair Set B',
    nameTh: 'เซตคู่ B',
    basePrice: 540,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862106489.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-duo',
    categoryId: 'set',
    name: 'DUO Set',
    nameTh: 'เซต DUO',
    basePrice: 520,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_01_Mar_2024_1709274138922.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-gomasaru',
    categoryId: 'set',
    name: 'GomaSaru Set',
    nameTh: 'เซตโกมะซารุ',
    basePrice: 190,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_17_Jan_2024_1705496971875.png',
    modifierGroups: [],
  },
  {
    id: 'set-family-a',
    categoryId: 'set',
    name: 'Family Set A+',
    nameTh: 'เซตครอบครัว A+',
    basePrice: 740,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_01_Mar_2024_1709267678770.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-family-b',
    categoryId: 'set',
    name: 'Family Set B+',
    nameTh: 'เซตครอบครัว B+',
    basePrice: 950,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_01_Mar_2024_1709268286029.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-yuzu-saru-ramen',
    categoryId: 'set',
    name: 'Yuzu Saru Ramen Set',
    nameTh: 'เซตยูซุ ซารุ ราเมง',
    basePrice: 180,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722413932284.png',
    modifierGroups: [],
  },
  {
    id: 'set-yuzu-saru-soba',
    categoryId: 'set',
    name: 'Yuzu Saru Soba Set',
    nameTh: 'เซตยูซุ ซารุ โซบะ',
    basePrice: 180,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722413887601.png',
    modifierGroups: [],
  },
  {
    id: 'set-yuzu-saru-udon',
    categoryId: 'set',
    name: 'Yuzu Saru Udon Set',
    nameTh: 'เซตยูซุ ซารุ อุด้ง',
    basePrice: 180,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722413841894.png',
    modifierGroups: [],
  },
  {
    id: 'set-a-plus-up-sauce',
    categoryId: 'set',
    name: 'A+ UP Sauce Set',
    nameTh: 'เซต A+ UP ซ่า',
    basePrice: 320,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746770209971.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'set-a-plus-double-sauce',
    categoryId: 'set',
    name: 'A+ Double Sauce Set',
    nameTh: 'เซต A+ Double ซ่า',
    basePrice: 340,
    thumbnailPlaceholder: '🍱',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746770173267.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },

  // ── ราเมนร้อน (A RAMEN HOT) ───────────────────────────────────────────────
  {
    id: 'ramen-original',
    categoryId: 'ramen-hot',
    name: 'Original Ramen',
    nameTh: 'ราเมง สูตรต้นตำรับ',
    basePrice: 160,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862381304.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'ramen-custom',
    categoryId: 'ramen-hot',
    name: 'Custom Ramen',
    nameTh: 'ราเมงข้อสอบ',
    basePrice: 160,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862367794.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'ramen-a-plus-upsized',
    categoryId: 'ramen-hot',
    name: 'A+ Ramen - Upsized',
    nameTh: 'เอพลัสราเมง - อัปไซส์',
    basePrice: 220,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746768992404.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'ramen-a-plus-double-pork',
    categoryId: 'ramen-hot',
    name: 'A+ Ramen - Double Pork',
    nameTh: 'เอพลัสราเมง - ดับเบิ้ลพอร์ค',
    basePrice: 240,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746768967269.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },

  // ── ราเมนเย็น (A RAMEN COLD) ──────────────────────────────────────────────
  {
    id: 'cold-noodles',
    categoryId: 'ramen-cold',
    name: 'Cold Noodles',
    nameTh: 'บะหมี่เย็น',
    basePrice: 130,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862307573.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'cold-udon-thin',
    categoryId: 'ramen-cold',
    name: 'Cold Udon (Thin)',
    nameTh: 'อุด้งเย็น (เส้นเล็ก)',
    basePrice: 130,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862539697.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'cold-soba',
    categoryId: 'ramen-cold',
    name: 'Cold Soba',
    nameTh: 'โซบะเย็น',
    basePrice: 130,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862185700.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'goma-saru-ramen',
    categoryId: 'ramen-cold',
    name: 'Goma Saru Ramen',
    nameTh: 'โกมะซารุ ราเมง',
    basePrice: 130,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_17_Jan_2024_1705497000539.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'yuzu-saru-ramen',
    categoryId: 'ramen-cold',
    name: 'Yuzu Saru Ramen',
    nameTh: 'ยูซุ ซารุ ราเมง',
    basePrice: 140,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722414177013.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'yuzu-saru-soba',
    categoryId: 'ramen-cold',
    name: 'Yuzu Saru Soba',
    nameTh: 'ยูซุ ซารุ โซบะ',
    basePrice: 140,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722414059836.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },
  {
    id: 'yuzu-saru-udon',
    categoryId: 'ramen-cold',
    name: 'Yuzu Saru Udon',
    nameTh: 'ยูซุ ซารุ อุด้ง',
    basePrice: 140,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_31_Jul_2024_1722413988546.png',
    modifierGroups: RAMEN_MODIFIER_GROUPS,
  },

  // ── ข้าวหน้า (A DON) ──────────────────────────────────────────────────────
  {
    id: 'pork-chashu-don-sliced',
    categoryId: 'don',
    name: 'Pork Charsu Don (Sliced)',
    nameTh: 'ข้าวหน้าหมูชาชูเต๋า',
    basePrice: 160,
    thumbnailPlaceholder: '🍚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_01_Aug_2025_1754022850241.png',
    modifierGroups: [],
  },
  {
    id: 'shredded-pork-chashu-don',
    categoryId: 'don',
    name: 'Shredded Pork Charsu Don',
    nameTh: 'ข้าวหน้าหมูชาชูฉีก',
    basePrice: 160,
    thumbnailPlaceholder: '🍚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768455458924.png',
    modifierGroups: [],
  },
  {
    id: 'fried-chicken-karaage-don',
    categoryId: 'don',
    name: 'Fried Chicken Karaage Don',
    nameTh: 'ข้าวหน้าไก่คาราอาเกะ',
    basePrice: 160,
    thumbnailPlaceholder: '🍚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768455416807.png',
    modifierGroups: [],
  },

  // ── อาหารทานเล่น (APPETIZERS) ──────────────────────────────────────────────
  {
    id: 'karaage-l',
    categoryId: 'appetizers',
    name: 'Fried Chicken Karaage (L)',
    nameTh: 'ไก่ทอดคาราอาเกะ (L)',
    basePrice: 140,
    thumbnailPlaceholder: '🍗',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746773543413.png',
    modifierGroups: [],
  },
  {
    id: 'karaage-m',
    categoryId: 'appetizers',
    name: 'Fried Chicken Karaage (M)',
    nameTh: 'ไก่ทอดคาราอาเกะ (M)',
    basePrice: 90,
    thumbnailPlaceholder: '🍗',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746773509233.png',
    modifierGroups: [],
  },
  {
    id: 'gyoza',
    categoryId: 'appetizers',
    name: 'Gyoza',
    nameTh: 'เกี๊ยวซ่า',
    basePrice: 90,
    thumbnailPlaceholder: '🥟',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_16_May_2025_1747376386919.png',
    modifierGroups: [],
  },
  {
    id: 'cold-tofu',
    categoryId: 'appetizers',
    name: 'Cold Tofu',
    nameTh: 'เต้าหู้เย็น',
    basePrice: 90,
    thumbnailPlaceholder: '🧊',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862247387.png',
    modifierGroups: [],
  },
  {
    id: 'spicy-pork',
    categoryId: 'appetizers',
    name: 'Spicy Pork',
    nameTh: 'หมูซ่า',
    basePrice: 90,
    thumbnailPlaceholder: '🥩',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862506236.png',
    modifierGroups: [],
  },
  {
    id: 'pork-chashu-appetizer',
    categoryId: 'appetizers',
    name: 'Pork Charsu',
    nameTh: 'หมูชาชูเต๋า',
    basePrice: 90,
    thumbnailPlaceholder: '🥩',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862483786.png',
    modifierGroups: [],
  },
  {
    id: 'seaweed-salad',
    categoryId: 'appetizers',
    name: 'Seaweed Salad',
    nameTh: 'ยำสาหร่าย',
    basePrice: 50,
    thumbnailPlaceholder: '🥗',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746773578956.png',
    modifierGroups: [],
  },
  {
    id: 'edamame',
    categoryId: 'appetizers',
    name: 'Edamame',
    nameTh: 'ถั่วแระญี่ปุ่น',
    basePrice: 40,
    thumbnailPlaceholder: '🫘',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_09_May_2025_1746773609991.png',
    modifierGroups: [],
  },
  {
    id: 'shredded-pork-bun',
    categoryId: 'appetizers',
    name: 'Shredded Pork Bun',
    nameTh: 'บันหมูชาชูฉีก',
    basePrice: 90,
    thumbnailPlaceholder: '🥖',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456650130.png',
    modifierGroups: [],
  },
  {
    id: 'french-fries',
    categoryId: 'appetizers',
    name: 'French Fries',
    nameTh: 'เฟรนช์ฟรายส์',
    basePrice: 60,
    thumbnailPlaceholder: '🍟',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768383860682.png',
    modifierGroups: [],
  },
  {
    id: 'french-fries-shredded-pork',
    categoryId: 'appetizers',
    name: 'French Fries with Shredded Pork',
    nameTh: 'เฟรช์ฟรายส์หมูชาชูฉีก',
    basePrice: 90,
    thumbnailPlaceholder: '🍟',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768384042607.png',
    modifierGroups: [],
  },

  // ── เครื่องเคียง (SIDE DISHES) ─────────────────────────────────────────────
  {
    id: 'side-chashu-fatty',
    categoryId: 'sides',
    name: 'Pork Charsu (with fat)',
    nameTh: 'หมูชาชู (ติดมัน)',
    basePrice: 90,
    thumbnailPlaceholder: '🥩',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862448281.png',
    modifierGroups: [],
  },
  {
    id: 'side-chashu-lean',
    categoryId: 'sides',
    name: 'Pork Charsu (lean)',
    nameTh: 'หมูชาชู (ไม่ติดมัน)',
    basePrice: 90,
    thumbnailPlaceholder: '🥩',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862460633.png',
    modifierGroups: [],
  },
  {
    id: 'side-bamboo',
    categoryId: 'sides',
    name: 'Bamboo Shoots',
    nameTh: 'หน่อไม้',
    basePrice: 40,
    thumbnailPlaceholder: '🎋',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862429260.png',
    modifierGroups: [],
  },
  {
    id: 'side-wood-ear',
    categoryId: 'sides',
    name: 'Wood Ear Mushroom',
    nameTh: 'เห็ดหูหนูน้ำมันงา',
    basePrice: 30,
    thumbnailPlaceholder: '🍄',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862522114.png',
    modifierGroups: [],
  },
  {
    id: 'side-pickled-ginger',
    categoryId: 'sides',
    name: 'Pickled Ginger',
    nameTh: 'ขิงดอง',
    basePrice: 30,
    thumbnailPlaceholder: '🫚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861943458.png',
    modifierGroups: [],
  },
  {
    id: 'side-seaweed',
    categoryId: 'sides',
    name: 'Seaweed',
    nameTh: 'สาหร่าย',
    basePrice: 40,
    thumbnailPlaceholder: '🌿',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862395911.png',
    modifierGroups: [],
  },
  {
    id: 'side-green-onion',
    categoryId: 'sides',
    name: 'Green Onion (add)',
    nameTh: 'ต้นหอมเขียว (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🌿',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862221253.png',
    modifierGroups: [],
  },
  {
    id: 'side-white-onion',
    categoryId: 'sides',
    name: 'Japanese White Onion (add)',
    nameTh: 'ต้นหอมขาวญี่ปุ่น (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🧅',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862206106.png',
    modifierGroups: [],
  },
  {
    id: 'side-boiled-egg',
    categoryId: 'sides',
    name: 'Boiled Egg (add)',
    nameTh: 'ไข่ต้ม (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🥚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861971292.png',
    modifierGroups: [],
  },
  {
    id: 'side-boiled-egg-chashu-sauce',
    categoryId: 'sides',
    name: 'Boiled Egg (with Charsu sauce)',
    nameTh: 'ไข่ต้ม (ซอสชาชู)',
    basePrice: 30,
    thumbnailPlaceholder: '🥚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861960323.png',
    modifierGroups: [],
  },
  {
    id: 'side-ramen-noodles',
    categoryId: 'sides',
    name: 'Ramen Noodles (add)',
    nameTh: 'เส้นราเมง (เพิ่ม)',
    basePrice: 40,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862411561.png',
    modifierGroups: [],
  },
  {
    id: 'side-broth',
    categoryId: 'sides',
    name: 'Broth (add)',
    nameTh: 'น้ำซุป (เพิ่ม)',
    basePrice: 40,
    thumbnailPlaceholder: '🥣',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862263073.png',
    modifierGroups: [],
  },
  {
    id: 'side-japanese-rice',
    categoryId: 'sides',
    name: 'Japanese Rice',
    nameTh: 'ข้าวญี่ปุ่น',
    basePrice: 30,
    thumbnailPlaceholder: '🍚',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861905659.png',
    modifierGroups: [],
  },
  {
    id: 'side-a-ramen-chili',
    categoryId: 'sides',
    name: 'A Ramen Chili (add)',
    nameTh: 'พริกเอราเมง (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🌶️',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862041534.png',
    modifierGroups: [],
  },
  {
    id: 'side-garlic',
    categoryId: 'sides',
    name: 'Garlic (add)',
    nameTh: 'กระเทียม (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🧄',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861866490.png',
    modifierGroups: [],
  },
  {
    id: 'side-mayo-sauce',
    categoryId: 'sides',
    name: 'Mayo Sauce (add)',
    nameTh: 'ซอสมาโย (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🫙',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768384735114.png',
    modifierGroups: [],
  },
  {
    id: 'side-spicy-mayo',
    categoryId: 'sides',
    name: 'Spicy Mayo (add)',
    nameTh: 'ซอสซ่ามาโย (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🌶️',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768384982033.png',
    modifierGroups: [],
  },
  {
    id: 'side-chashu-mayo',
    categoryId: 'sides',
    name: 'Charsu Mayo (add)',
    nameTh: 'ซอสชาชูมาโย (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🫙',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768385099515.png',
    modifierGroups: [],
  },
  {
    id: 'side-tonkatsu-sauce',
    categoryId: 'sides',
    name: 'Tonkatsu Sauce (add)',
    nameTh: 'ซอสทงคัตสึ (เพิ่ม)',
    basePrice: 20,
    thumbnailPlaceholder: '🫙',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768385361675.png',
    modifierGroups: [],
  },
  {
    id: 'side-noodles-add',
    categoryId: 'sides',
    name: 'Ramen Noodles (add)',
    nameTh: 'เส้นบะหมี่ (เพิ่ม)',
    basePrice: 50,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456098149.png',
    modifierGroups: [],
  },
  {
    id: 'side-soba-noodles',
    categoryId: 'sides',
    name: 'Soba Noodles (add)',
    nameTh: 'เส้นโซบะ (เพิ่ม)',
    basePrice: 50,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456239557.png',
    modifierGroups: [],
  },
  {
    id: 'side-cold-udon-thin',
    categoryId: 'sides',
    name: 'Cold Udon (thin) (add)',
    nameTh: 'เส้นอุด้งเย็นเส้นเล็ก (เพิ่ม)',
    basePrice: 50,
    thumbnailPlaceholder: '🍜',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456330844.png',
    modifierGroups: [],
  },
  {
    id: 'side-shredded-pork',
    categoryId: 'sides',
    name: 'Shredded Pork',
    nameTh: 'หมูชาชูฉีก',
    basePrice: 40,
    thumbnailPlaceholder: '🥩',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768458261835.png',
    modifierGroups: [],
  },

  // ── เครื่องดื่ม (BEVERAGES) ─────────────────────────────────────────────────
  {
    id: 'pure-matcha-cold',
    categoryId: 'drinks',
    name: 'Pure Matcha Cold Tea',
    nameTh: 'เพียวมัทฉะเย็น',
    basePrice: 50,
    thumbnailPlaceholder: '🍵',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862013444.png',
    modifierGroups: [],
  },
  {
    id: 'green-tea-hot',
    categoryId: 'drinks',
    name: 'Green Tea (hot)',
    nameTh: 'ชาเขียวร้อน',
    basePrice: 50,
    thumbnailPlaceholder: '🍵',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862027063.png',
    modifierGroups: [],
  },
  {
    id: 'beer',
    categoryId: 'drinks',
    name: 'Beer',
    nameTh: 'เบียร์',
    basePrice: 90,
    thumbnailPlaceholder: '🍺',
    imagePath: 'https://aramen-locationcms.s3.ap-southeast-1.amazonaws.com/aramen-menu/menuyvjzhaxlov',
    modifierGroups: [],
  },
  {
    id: 'water',
    categoryId: 'drinks',
    name: 'Water',
    nameTh: 'น้ำเปล่า',
    basePrice: 20,
    thumbnailPlaceholder: '💧',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862277312.png',
    modifierGroups: [],
  },
  {
    id: 'coke-zero',
    categoryId: 'drinks',
    name: 'Coke Zero',
    nameTh: 'โค้กซีโร่',
    basePrice: 30,
    thumbnailPlaceholder: '🥤',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861997258.png',
    modifierGroups: [],
  },
  {
    id: 'coke',
    categoryId: 'drinks',
    name: 'Coke',
    nameTh: 'โค้ก',
    basePrice: 30,
    thumbnailPlaceholder: '🥤',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692861986168.png',
    modifierGroups: [],
  },
  {
    id: 'yuzu-honey',
    categoryId: 'drinks',
    name: 'Yuzu Honey',
    nameTh: 'ยูซุน้ำผึ้ง',
    basePrice: 80,
    thumbnailPlaceholder: '🍯',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862331818.png',
    modifierGroups: [],
  },
  {
    id: 'yuzu-honey-soda',
    categoryId: 'drinks',
    name: 'Yuzu Honey Soda',
    nameTh: 'ยูซุน้ำผึ้งโซดา',
    basePrice: 90,
    thumbnailPlaceholder: '🥤',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_24_Aug_2023_1692862346761.png',
    modifierGroups: [],
  },
  {
    id: 'pure-matcha-latte',
    categoryId: 'drinks',
    name: 'Pure Matcha Latte',
    nameTh: 'เพียวมัทฉะลาเต้',
    basePrice: 80,
    thumbnailPlaceholder: '🍵',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_23_Feb_2026_1771825953681.png',
    modifierGroups: [],
  },
  {
    id: 'pure-matcha-strawberry-latte',
    categoryId: 'drinks',
    name: 'Pure Matcha Strawberry Latte',
    nameTh: 'เพียวมัทฉะลาเต้สตรอว์เบอร์รี่',
    basePrice: 95,
    thumbnailPlaceholder: '🍓',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_23_Feb_2026_1771826080111.png',
    modifierGroups: [],
  },

  // ── ของหวาน (DESSERTS) ──────────────────────────────────────────────────────
  {
    id: 'soft-serve-milk',
    categoryId: 'desserts',
    name: 'Soft Serve (Milk)',
    nameTh: 'ซอฟต์เสิร์ฟ (นม)',
    basePrice: 19,
    thumbnailPlaceholder: '🍦',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456617260.png',
    modifierGroups: [],
  },
  {
    id: 'soft-serve-chocolate',
    categoryId: 'desserts',
    name: 'Soft Serve (Chocolate)',
    nameTh: 'ซอฟต์เสิร์ฟ (ช็อกโกแลต)',
    basePrice: 19,
    thumbnailPlaceholder: '🍦',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_15_Jan_2026_1768456596220.png',
    modifierGroups: [],
  },
  {
    id: 'soft-serve-mix',
    categoryId: 'desserts',
    name: 'Soft Serve (Milk & Chocolate)',
    nameTh: 'ซอฟต์เสิร์ฟ (นม & ช็อกโกแลต)',
    basePrice: 19,
    thumbnailPlaceholder: '🍦',
    imagePath: 'https://cdn.a-ramen.com/website/static/menu/menu_img_0_14_Jan_2026_1768386716824.png',
    modifierGroups: [],
  },
]
